application:
  name: GateKeeper AI

camera:
  width: 1640
  height: 1232
  fps: 1

debug:
  save_latest: true

logging:
  level: INFO

motion:
  enabled: true
  threshold: 25
  min_area: 1000
  end_delay_seconds: 2
